apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rbac-ingress
  namespace: rbac
spec:
  ingressClassName: nginx
  rules:
    - host: www.rbac-service.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rbac-frontend
                port:
                  number: 80

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: rbac-service
                port:
                  number: 80

